name: Trigger Downstream Deployments

on:
  push:
    branches: [main]
    paths:
      - 'modules/vpc/**'
      - 'modules/certificates/**'
      - 'modules/ram-tagging/**'

jobs:
  notify-iac-aws:
    name: Notify iac-aws Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Determine changed modules
        id: changes
        run: |
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Check which modules changed
          if echo "$CHANGED_FILES" | grep -q "modules/vpc/"; then
            echo "vpc_changed=true" >> $GITHUB_OUTPUT
          fi
          
          if echo "$CHANGED_FILES" | grep -q "modules/certificates/"; then
            echo "cert_changed=true" >> $GITHUB_OUTPUT
          fi
          
          if echo "$CHANGED_FILES" | grep -q "modules/ram-tagging/"; then
            echo "ram_changed=true" >> $GITHUB_OUTPUT
          fi
          
          # Get commit information
          echo "commit_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "commit_message=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
      
      - name: Trigger VPC deployment in iac-aws
        if: steps.changes.outputs.vpc_changed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CROSS_REPO_TOKEN }}  # Needs a PAT with repo scope
          repository: AdaptiveWorX/iac-aws
          event-type: module-change
          client-payload: |
            {
              "module_path": "modules/vpc",
              "commit_sha": "${{ steps.changes.outputs.commit_sha }}",
              "commit_message": "${{ steps.changes.outputs.commit_message }}",
              "repository": "${{ github.repository }}"
            }
      
      - name: Summary
        run: |
          echo "## 📤 Downstream Notifications Sent"
          echo ""
          if [[ "${{ steps.changes.outputs.vpc_changed }}" == "true" ]]; then
            echo "✅ VPC module changes → Notified iac-aws repository"
          fi
          if [[ "${{ steps.changes.outputs.cert_changed }}" == "true" ]]; then
            echo "✅ Certificate module changes → Ready for downstream triggers"
          fi
          if [[ "${{ steps.changes.outputs.ram_changed }}" == "true" ]]; then
            echo "✅ RAM tagging module changes → Ready for downstream triggers"
          fi
          echo ""
          echo "**Commit**: ${{ steps.changes.outputs.commit_sha }}"
          echo "**Message**: ${{ steps.changes.outputs.commit_message }}"
